# Generated by Django 3.2.5 on 2021-11-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='terms_check',
            field=models.BooleanField(null=True),
        ),
    ]
