# Generated by Django 3.2.5 on 2021-11-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_terms_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='terms_check',
            field=models.BooleanField(default=False, verbose_name='First Check'),
        ),
    ]
