# Generated by Django 3.2.5 on 2021-11-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_terms_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='terms_check',
        ),
    ]
