# Generated by Django 3.2.5 on 2021-08-01 20:28

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(default='', max_length=200)),
                ('medicine_quantity', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(default='2021-07-29')),
                ('post_date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('address', models.TextField(default='')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('author', models.ManyToManyField(blank=True, default='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
