# Generated by Django 3.2.5 on 2021-08-05 10:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicinePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(default='', max_length=200)),
                ('medicine_quantity', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('post_date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('medicine_image', models.ImageField(default='/images/PNG_transparency_demonstration_1.png', upload_to='images/')),
                ('phone_number', models.CharField(default='', max_length=200)),
                ('post_type', models.CharField(choices=[('Donate', 'Donate'), ('Receive', 'Receive')], default='JANUARY', max_length=20)),
                ('address', models.TextField(default='')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
