# Generated by Django 3.2.5 on 2021-08-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='medicine_quantity',
            field=models.IntegerField(),
        ),
    ]
