# Generated by Django 3.2.5 on 2021-08-05 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20210805_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinepost',
            name='author',
        ),
        migrations.AddField(
            model_name='medicinepost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
