# Generated by Django 3.2.5 on 2021-08-01 21:40

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_rename_post_havemedicinepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedMedicinePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(default='', max_length=200)),
                ('medicine_quantity', models.IntegerField()),
                ('post_date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('address', models.TextField(default='')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('author', models.ManyToManyField(blank=True, default='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
