# Generated by Django 3.2.5 on 2021-09-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_medicinepost_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepost',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
    ]
