# Generated by Django 3.2.5 on 2021-09-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_medicinepost_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepost',
            name='medicine_image',
            field=models.ImageField(blank=True, default='/logo.png', null=True, upload_to='images/'),
        ),
    ]
