# Generated by Django 3.2.5 on 2021-08-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_needmedicinepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='needmedicinepost',
            name='medicine_image',
            field=models.ImageField(blank=True, null=True, upload_to='.static/images'),
        ),
    ]
