# Generated by Django 3.2.5 on 2021-08-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_needmedicinepost_medicine_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needmedicinepost',
            name='medicine_image',
        ),
        migrations.AddField(
            model_name='havemedicinepost',
            name='medicine_image',
            field=models.ImageField(blank=True, null=True, upload_to='.static/images'),
        ),
    ]
