# Generated by Django 3.2.5 on 2021-08-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210802_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='havemedicinepost',
            name='address_google_maps',
        ),
        migrations.RemoveField(
            model_name='havemedicinepost',
            name='geolocation',
        ),
    ]
