# Generated by Django 3.2.5 on 2021-08-03 09:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20210802_2018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HaveMedicinePost',
            new_name='MedicinePost',
        ),
        migrations.DeleteModel(
            name='NeedMedicinePost',
        ),
    ]
