# Generated by Django 3.2.5 on 2021-11-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_medicinepost_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepost',
            name='expiry_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='medicinepost',
            name='medicine_image',
            field=models.ImageField(default='/logo.png', upload_to='images/'),
        ),
    ]
