# Generated by Django 3.2.5 on 2021-11-09 20:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211108_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepost',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
