# Generated by Django 3.2.5 on 2021-08-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210803_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinepost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('donate', 'donate'), ('receive', 'receive')], max_length=10),
        ),
    ]
