# Generated by Django 3.2.5 on 2021-08-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_medicinepost_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinepost',
            name='post_type',
        ),
    ]
