# Generated by Django 3.2.5 on 2021-11-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_medicinepost_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepost',
            name='expiry_date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
