# Generated by Django 3.2.5 on 2021-08-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210804_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepost',
            name='medicine_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
