# Generated by Django 3.2.5 on 2021-08-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_medicinepost_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepost',
            name='medicine_image',
            field=models.ImageField(default='/images/PNG_transparency_demonstration_1.png', upload_to='images/'),
        ),
    ]
