# Generated by Django 3.2.5 on 2021-11-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_medicinepost_terms_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepost',
            name='medicine_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
