# Generated by Django 3.2.5 on 2021-08-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_medicinepost_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepost',
            name='phone_number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
