# Generated by Django 3.2.5 on 2021-11-13 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_medicinepost_medicine_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinepost',
            name='terms_check',
        ),
    ]
