# Generated by Django 3.2.5 on 2021-12-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_medicinepost_terms_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepost',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
    ]
