# Generated by Django 3.2.5 on 2021-12-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_medicinepost_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepost',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Expiry Date'),
        ),
    ]
