# Generated by Django 3.2.5 on 2021-12-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_medicinepost_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepost',
            name='post_type',
            field=models.CharField(choices=[('Donate', 'Donation'), ('Receive', 'Request')], max_length=20),
        ),
    ]
