# Generated by Django 3.2.5 on 2021-12-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_medicinepost_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinepost',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
