# Generated by Django 3.2.5 on 2021-12-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_medicinepost_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepost',
            name='post_type',
            field=models.CharField(choices=[('', 'Select Post Type'), ('Donate', 'Donation'), ('Receive', 'Request')], max_length=20),
        ),
    ]
