# Generated by Django 3.2.5 on 2021-12-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_medicinepost_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepost',
            name='medicine_image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
