# Generated by Django 3.2.5 on 2021-12-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_medicinepost_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepost',
            name='medicine_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
