# Generated by Django 3.2.5 on 2021-08-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_medicinepost_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepost',
            name='post_type',
            field=models.CharField(choices=[('Donation', 'Donation'), ('In Need Of', 'In Need Of')], default='JANUARY', max_length=20),
        ),
    ]
